### Healthcheck
GET http://localhost:8000/healthz

### Create job
POST http://localhost:8000/v1/lyrics/jobs
Content-Type: application/json

{
  "audioUrl": "https://example-bucket.s3.amazonaws.com/presigned",
  "languageHint": "en",
  "trackName": "Someone Like You",
  "artistName": "Adele",
  "durationMs": 285000,
  "isCustomCover": false
}

### Poll job
GET http://localhost:8000/v1/lyrics/jobs/replace-with-job-id
